name: CI Pipeline - Maven + Selenium + JMeter + SonarQube

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar Mozilla Firefox
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox

      - name: Cachear dependencias Maven
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Compilar con Maven
        run: mvn clean install -DskipTests
        working-directory: monitoreo-peso

      - name: Construir y ejecutar pruebas
        working-directory: monitoreo-peso
        run: mvn clean test

      - name: Instalar JMeter
        working-directory: monitoreo-peso
        run: |
          wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz
          export PATH=$PATH:$PWD/apache-jmeter-5.6.3/bin

      - name: Ejecutar pruebas de rendimiento con JMeter
        working-directory: monitoreo-peso
        run: |
          mvn verify

      - name: Publicar reporte de JMeter
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reporte-jmeter
          path: monitoreo-peso/target/reporte/
     
      #- name: Construir y analizar con SonarQube
      #  working-directory: monitoreo-peso
      #  run: mvn verify sonar:sonar -Dsonar.projectKey=monitoreo-peso \
      #                              -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
      #                              -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
      #- name: Publicar reporte de SonarQube
      #  if: always()
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: sonar-reports
          
      - name: Subir reportes de pruebas (Surefire)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: monitoreo-peso/target/surefire-reports/


